-- 2018-10-10
ALTER TABLE E_JOB ADD (AUTO_RENEW NUMBER(1) DEFAULT 0);

COMMENT ON COLUMN "E_JOB"."AUTO_RENEW" IS '是否到期后自动续费，布尔值，0-false，1-true';

-- 2018-10-12 职位置顶
ALTER TABLE E_JOB ADD (IS_TOP NUMBER(1) DEFAULT 0);
COMMENT ON COLUMN "E_JOB"."IS_TOP" IS '职位是否置顶，排序用的，布尔值，0-false，1-true';

ALTER TABLE E_JOB ADD (TOP_SERVICE_EXP_DATE DATE);
COMMENT ON COLUMN "E_JOB"."TOP_SERVICE_EXP_DATE" IS '置顶服务过期时间';