CREATE TABLE "U_JOB_COMMUNICATED" (
"SEEKER_ID" NUMBER(10) NULL,
"JOB_ID" NUMBER(10) NULL,
"CREATE_AT"  DATE  DEFAULT sysdate,
PRIMARY KEY ("SEEKER_ID", "JOB_ID")
);

COMMENT ON TABLE U_JOB_COMMUNICATED
is '中间表，用户沟通过哪个职位'
/