-- 2018-10-09 是否已面试
ALTER TABLE U_JOB_APPLY ADD (INTERVIEW_STATUS NUMBER(1) DEFAULT -1);
ALTER TABLE U_JOB_APPLY ADD(MOBILE VARCHAR2(40));

COMMENT ON COLUMN U_JOB_APPLY.MOBILE IS '面试联系电话';
comment on column U_JOB_APPLY.INTERVIEW_STATUS
is '是否已面试，-1未知状态(用户没有标记是否已经面试)， 0-未面试，1-已面试'
/