-- 2018-10-08
ALTER TABLE U_SEEKER ADD REGION_CODE VARCHAR2(20);

-- 2018-10-09
ALTER TABLE E_EMPLOYER ADD(IMAGES VARCHAR2(4000 BYTE));
ALTER TABLE E_EMPLOYER ADD(WELFARE VARCHAR2(40));

COMMENT ON COLUMN "E_EMPLOYER"."IMAGES" IS '公司图片';
COMMENT ON COLUMN "E_EMPLOYER"."WELFARE" IS '公司福利';