-- 2018-10-09
CREATE TABLE U_TWITTER_LIKE(
    TWITTER_ID NUMBER(10,0),
    USER_ID  NUMBER(10,0)
    CREATE_AT DATE DEFAULT sysdate
)
alter table U_TWITTER_LIKE add constraint TWITTER_LIKES_PKEY primary key (TWITTER_ID,USER_ID);
COMMENT ON COLUMN "U_TWITTER_LIKE"."USER_ID" IS '点赞者id';
COMMENT ON COLUMN "U_TWITTER_LIKE"."TWITTER_ID" IS '动态ID';
