-- 2018-10-09
CREATE TABLE U_TWITTER_COMMENTS(
    ID NUMBER(10,0) NOT NULL PRIMARY KEY,
    TWITTER_ID NUMBER(10,0),
    USER_ID  NUMBER(10,0),
    CONTENT VARCHAR2(4000 BYTE),
    ANONYMOUS NUMBER(1,0),
    STATUS NUMBER(1,0) DEFAULT 1,
    CREATE_AT DATE DEFAULT sysdate,
    UPDATE_AT DATE
)
CREATE SEQUENCE SEQ_U_TWITTER_COMMENTS INCREMENT BY 1 START WITH 1 ;
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."USER_ID" IS '评论者id';
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."TWITTER_ID" IS '动态ID';
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."CONTENT" IS '评论内容';
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."ANONYMOUS" IS '评论者是否匿名 1:不匿名 0：匿名';
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."STATUS" IS '是否删除 1:未删除 0：删除';
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."CREATE_AT" IS '创建时间';
COMMENT ON COLUMN "U_TWITTER_COMMENTS"."UPDATE_AT" IS '修改时间';